// npm run beats [-- --out beats.md] [--manifest <path>]
// Writes the manifest as a readable view into beats.md, between
// <!-- beats:start --> and <!-- beats:end -->. Text outside the markers is
// hand-written (throughline, arc, rate, set pieces) and never touched.
import { parseArgs } from "node:util";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { cue, script, words, hold, seconds, totals, mmss, WPM, type Beat, type Talk } from "../src/runtime/manifest.ts";

const { values: o } = parseArgs({ options: { out: { type: "string" }, manifest: { type: "string" } } });
const m = (await import(pathToFileURL(resolve(o.manifest ?? "src/beats.ts")).href)) as { beats: Beat[]; talk?: Talk };
const wpm = m.talk?.wpm ?? WPM;
const START = "<!-- beats:start -->";
const END = "<!-- beats:end -->";

const entry = (b: Beat, i: number) =>
  [
    `### ${i + 1}. ${b.section} · ${b.id} · ${b.label}${b.kind && b.kind !== "content" ? ` (${b.kind})` : ""}`,
    "",
    ...(b.job ? [`- **Job:** ${b.job}`] : []),
    ...(b.sees ? [`- **Sees:** ${b.sees}`] : []),
    `- **Cue:** ${cue(b.notes)}`,
    `- **Time:** ${words(b.notes)} words + ${hold(b)} s = ${mmss(seconds(b, wpm))}`,
    ...(b.assets?.length ? [`- **Assets:** ${b.assets.join(", ")}`] : []),
    ...(b.fallback ? [`- **Fallback:** ${b.fallback}`] : []),
    "",
    script(b.notes)
      .split("\n")
      .map((l) => `> ${l}`)
      .join("\n"),
  ].join("\n");

const slot = m.talk?.slot ?? 0;
const t = totals(m.beats, wpm, slot);
const block = [
  START,
  "<!-- generated by `npm run beats` from src/beats.ts: edit the manifest, not this block -->",
  "",
  ...m.beats.map((b, i) => entry(b, i) + "\n"),
  `**Totals:** speech ${mmss(t.speech)} + holds ${mmss(t.holds)} = total ${mmss(t.total)} at ${wpm} wpm${slot ? `, ${t.share}% of a ${slot} min slot` : ""}`,
  END,
].join("\n");

const file = resolve(o.out ?? "beats.md");
const md = existsSync(file) ? readFileSync(file, "utf8") : "";
const a = md.indexOf(START);
const z = md.indexOf(END);
const next = a >= 0 && z > a ? md.slice(0, a) + block + md.slice(z + END.length) : `${md}${md && !md.endsWith("\n\n") ? (md.endsWith("\n") ? "\n" : "\n\n") : ""}${block}\n`;
writeFileSync(file, next);
console.log(`beats -> ${file}`);
